### ISSUE TITLE
Cylc monitor broken on master when USER_AT_HOST is given

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3143]
I was testing Cylc for another pull request related to parsec, and one functional test was broken, I believe it was `/tests/cylc-scan/03-monitor.t`. It was broken because of my change in parsec, so I imported the suite from `03-monitor.t` and executed with `cylc run 03-monitor`.

The suite runs for one minute, during which I had time to run `cylc monitor ...` as in the `03-monitor.t` test. In the test, it runs with `--once`, which I suspect doesn't wait for Cylc monitor to finish.

However, in my case I was impressed by Cylc monitor (first time I ever used it), so kept looking to see what would happen. Then it updated the task status, and finally broke with an exception. Fixing conflicts on a branch, but will update the issue later to include the exception here.

**Comment by kinow** [comment]
Here's the error, which does not occur if you run with `--once`.

```
03-monitor - 1 tasks                                                                        cylc-monitor
runaheadwaitingheldqueuedexpiredreadysubmit-failedsubmit-retryingsubmittedretryingrunningfailedsucceeded
updated: 2019-05-01T21:27:21+12:00
state summary: 1 
__________________________________________________________________r_u_n_n_i_n_g___t_o___s_t_o_p___a_t__1
1 foo
ERROR Request returned error: Suite "03-monitor" already stopped
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/cylc-flow/bin/cylc-monitor", line 148, in run
    self.pclient('get_suite_state_summary')[0:2])
  File "/home/kinow/Development/python/workspace/cylc-flow/lib/cylc/network/client.py", line 180, in serial_request
    self.async_request(command, args, timeout))
  File "/home/kinow/Development/python/anaconda3/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/kinow/Development/python/anaconda3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/kinow/Development/python/workspace/cylc-flow/lib/cylc/network/client.py", line 144, in async_request
    self.timeout_handler()
  File "/home/kinow/Development/python/workspace/cylc-flow/lib/cylc/network/client.py", line 236, in <lambda>
    timeout_handler=lambda: cls._timeout_handler(suite, host, port)
  File "/home/kinow/Development/python/workspace/cylc-flow/lib/cylc/network/client.py", line 270, in _timeout_handler
    raise ClientError('Suite "%s" already stopped' % suite)
cylc.exceptions.ClientError: Request returned error: Suite "03-monitor" already stopped

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/bin/cylc-monitor", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/kinow/Development/python/workspace/cylc-flow/bin/cylc-monitor", line 274, in <module>
    SuiteMonitor().run()
  File "/home/kinow/Development/python/workspace/cylc-flow/lib/cylc/terminal.py", line 65, in wrapper
    function(*args, **kwargs)
  File "/home/kinow/Development/python/workspace/cylc-flow/bin/cylc-monitor", line 152, in run
    options.comms_timeout)
  File "/home/kinow/Development/python/workspace/cylc-flow/bin/cylc-monitor", line 108, in reset
    suite, owner, host, port, timeout)
  File "/home/kinow/Development/python/workspace/cylc-flow/lib/cylc/network/client.py", line 236, in __new__
    timeout_handler=lambda: cls._timeout_handler(suite, host, port)
  File "/home/kinow/Development/python/workspace/cylc-flow/lib/cylc/network/client.py", line 99, in __init__
    self.socket = CONTEXT.socket(zmq.REQ)
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/site-packages/zmq/sugar/context.py", line 146, in socket
    s = self._socket_class(self, socket_type, **kwargs)
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/site-packages/zmq/_future.py", line 136, in __init__
    self.io_loop = io_loop or self._default_loop()
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/site-packages/zmq/asyncio/__init__.py", line 28, in _default_loop
    return asyncio.get_event_loop()
  File "/home/kinow/Development/python/anaconda3/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.
Exception ignored in: <function Socket.__del__ at 0x7f5f3816bb70>
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/site-packages/zmq/sugar/socket.py", line 67, in __del__
    self.close()
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/site-packages/zmq/_future.py", line 150, in close
    for event in list(chain(self._recv_futures, self._send_futures)):
TypeError: 'NoneType' object is not iterable
```

**Comment by kinow** [comment]
Updated issue title, as the traceback is printed only when a `USER_AT_HOST` argument is passed. Otherwise it exists with

```
...
20130812T0000Z foo bar
ERROR Request returned error: Suite "five" already stopped
ClientError: Request returned error: Contact info not found for suite "five", suite not running?
```

**Comment by kinow** [comment]
When a `host:port` is not provided in the arguments, then it calls `SuiteSrvFilesManager().load_contact_file`, which fails to find the contact file with a `ClientError`. `ClientError`s are expected, so there is no traceback.

On the other hand, when the user provides the `host:port`, it skips the `load_contact_file`, and goes straight to the `ZMQClient.__init__()`, where it tries to use the PyZMQ context object after the main loop is gone, resulting in a `RuntimeError`.

**Comment by kinow** [comment]
Working with no issues now.

![image](https://user-images.githubusercontent.com/304786/64138429-32b66d80-ce51-11e9-870f-c075613dd20f.png)

**Comment by matthewrmshin** [comment]
(Assumed that a recent change has fixed the issue?)

**Comment by kinow** [comment]
Yes, though I have no idea which change it was.
