### ISSUE TITLE
Traceback when running cylc search five ?

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3240]
**Describe the bug**

I was playing with different Cylc commands when I noticed that `cylc search five ?` would result in a traceback printed.

**Release version(s) and/or repository branch(es) affected?**

`master`

**Steps to reproduce the bug**

`cylc search $valid-suite ?`

**Expected behavior**

Same as searching `cylc search five oranges`.

**Screenshots**

**Additional context**

Traceback:

```python
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/bin/cylc-search", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/kinow/Development/python/workspace/cylc-flow/bin/cylc-search", line 195, in <module>
    main()
  File "/home/kinow/Development/python/workspace/cylc-flow/cylc/flow/terminal.py", line 137, in wrapper
    wrapped_function(*wrapped_args, **wrapped_kwargs)
  File "/home/kinow/Development/python/workspace/cylc-flow/bin/cylc-search", line 133, in main
    if re.search(pattern, line):
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/re.py", line 183, in search
    return _compile(pattern, flags).search(string)
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/sre_parse.py", line 651, in _parse
    source.tell() - here + len(this))
re.error: nothing to repeat at position 0
```

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by kinow** [comment]
It looks like this one was fixed by some recent commit. With `master`:

```bash
(venv) kinow@kinow-VirtualBox:~/Development/python/workspace/cylc-flow$ cylc search five oranges

Suite five has no bin directory
```
