### ISSUE TITLE
[discussion] Delegate dependency checking to package manager tools (conda/pip/etc)

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#3365]
**Describe exactly what you would like to see in an upcoming release**

`cylc check-software` is a useful command, that tries to tell the user what is the status of the Cylc environment, which versions are installed or missing, etc.

Different than Cylc 7, we have way more dependencies. And issues with dependencies result in exceptions being raised, with more information about why the error happened.

At the moment these exceptions are printed back to the user. We could interpret these exceptions and try to present in a user-friendly way.

This issue is a a discussion around delegating that to tools that are better at doing that. I am familiar with `pip`, but there should be something for `conda`, or if the user installed directly in the system, then `yum`, `apt`, `zypper`, etc, should be able to check for dependency issues.

**Additional context**

The happy-path here, when everything works, can be easily reproduced with `pip install .[all]`ing for `cylc-flow`, then `cylc check-software`:

```bash
$ cylc check-software
Checking your software...

Individual results:
==========================================================================================
Package (version requirements)                                     Outcome (version found)
==========================================================================================
                                   *REQUIRED SOFTWARE*                                   
Python (3.7+).....................................FOUND & min. version MET (3.7.3.final.0)
Python:zmq (any)............................................................FOUND (18.0.2)
Python:jose (any)............................................................FOUND (3.0.1)
Python:graphene (any)........................................................FOUND (2.1.8)
Python:colorama (any)........................................................FOUND (0.4.1)
Python:ansimarkup (any)......................................................FOUND (1.4.0)
Python:protobuf (3.7.0+)..................................FOUND & min. version MET (3.9.1)

                   *OPTIONAL SOFTWARE for the configuration templating*                   
Python:EmPy (3.3.4+)......................................FOUND & min. version MET (3.3.4)
==========================================================================================

Summary:
                               ****************************                               
                                  Core requirements: ok                                  
                                  Full-functionality: ok                                  
                               ****************************
```

If the user accidentally removed the `colorama` package (e.g. IT Ops removed an RPM that was providing this package, or some other process/user removed it manually with conda/pip/rm/etc):

```bash
$ pip uninstall colorama -y
Uninstalling colorama-0.4.1:
  Successfully uninstalled colorama-0.4.1
$ cylc check-software
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/bin/cylc-check-software", line 4, in <module>
    __import__('pkg_resources').require('cylc-flow==8.0a0')
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'colorama==0.4.*' distribution was not found and is required by cylc-flow
```

Which is not really nice, but at least tells the user that there's something wrong in the environment, and also that it is probably related to colorama.

Similarly, if the user accidentally installed an older version of `promise` (used by `graphene`), our traceback also gives an idea of what could be wrong:

```bash
$ pip uninstall -y promise
Uninstalling promise-2.2.1:
  Successfully uninstalled promise-2.2.1
$ pip install promise==0.4.0
Collecting promise==0.4.0
  Downloading https://files.pythonhosted.org/packages/54/4c/7f11cf1e670e537391ab304c160b8c5cdff756cc70bb5d8b1c2774a2117a/promise-0.4.tar.gz
Building wheels for collected packages: promise
  Building wheel for promise (setup.py) ... done
  Created wheel for promise: filename=promise-0.4-cp37-none-any.whl size=6560 sha256=c9bfed2e2cf63f181bfeb5fd7036bfae4fa3fb49f89a407401b278c183f70c37
  Stored in directory: /home/kinow/.cache/pip/wheels/99/75/1e/d23c2af21c35ddc7771a9f5c586d7e68dcea436a42cb8ebb5b
Successfully built promise
ERROR: graphql-relay 2.0.0 has requirement promise<3,>=2.2, but you'll have promise 0.4 which is incompatible.
ERROR: graphql-core 2.2.1 has requirement promise>=2.1, but you'll have promise 0.4 which is incompatible.
Installing collected packages: promise
Successfully installed promise-0.4
$ cylc check-software
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (promise 0.4 (/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/site-packages), Requirement.parse('promise>=2.1'), {'graphql-core'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/bin/cylc-check-software", line 4, in <module>
    __import__('pkg_resources').require('cylc-flow==8.0a0')
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/kinow/Development/python/workspace/cylc-flow/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'promise>=2.1' distribution was not found and is required by graphql-core
```

Now compare with the output of the `pip` command to check for dependencies.

```bash
$ pip check
graphql-relay 2.0.0 has requirement promise<3,>=2.2, but you have promise 0.4.
graphql-core 2.2.1 has requirement promise>=2.1, but you have promise 0.4.
```

A user familiar with pip may even fix it by copying the requirement from the message and installing it.

```bash
$ pip install "promise<3,>=2.2"
Collecting promise<3,>=2.2
Requirement already satisfied: six in ./venv/lib/python3.7/site-packages (from promise<3,>=2.2) (1.12.0)
Installing collected packages: promise
  Found existing installation: promise 0.4
    Uninstalling promise-0.4:
      Successfully uninstalled promise-0.4
Successfully installed promise-2.2.1
```

IMO `cylc check-software` will have more challenges as our dependency stack grows, and there are alternatives that could give the user better diagnostics.

Furthermore, users won't have `cylc check-software` for Cylc UI Server or other Cylc Python projects, unless we either add it to `cylc-flow`'s subcommand, or replicate the logic there.

**Pull requests welcome!**

**Comment by kinow** [comment]
Related #3208 (or I can close this issue and move it as a comment there?)

**Comment by matthewrmshin** [comment]
Please merge #3208 with this one, (i.e. close either one will do).
