### ISSUE TITLE
traceback restarting suite

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3865]
The following traceback was reported on restarting a suite:

```
2020-10-13T13:48:17Z INFO - LOADING task action timers
2020-10-13T13:48:17Z INFO - + glm_run_plotting.20201012T0000Z [u'try_timers', u'retrying']
2020-10-13T13:48:17Z INFO - + glm_run_plotting.20201012T0000Z [u'try_timers', u'submit-retrying']
2020-10-13T13:48:17Z INFO - + glu_housekeep.20201012T0000Z [u'try_timers', u'retrying']
2020-10-13T13:48:17Z INFO - + glu_housekeep.20201012T0000Z [u'try_timers', u'submit-retrying']
2020-10-13T13:48:17Z INFO - + prune_logs.20201012T0000Z poll_timer
2020-10-13T13:48:17Z INFO - + prune_logs.20201012T0000Z [u'try_timers', u'retrying']
2020-10-13T13:48:17Z INFO - + prune_logs.20201012T0000Z [u'try_timers', u'submit-retrying']
2020-10-13T13:48:17Z INFO - [prune_logs.20201012T0000Z] status=submitted: (polled)succeeded at 2020-10-13T12:19:54Z for job(01)
2020-10-13T13:48:17Z INFO - [prune_logs.20201012T0000Z] -Succeeded with outputs not completed: 
	  started
2020-10-13T13:48:17Z ERROR - u'glm_run_plotting.20201012T0000Z'
	Traceback (most recent call last):
	  File "cylc-7.8.6/lib/cylc/scheduler.py", line 247, in start
	    self.run()
	  File "cylc-7.8.6/lib/cylc/scheduler.py", line 1596, in run
	    self.process_task_pool()
	  File "cylc-7.8.6/lib/cylc/scheduler.py", line 1241, in process_task_pool
	    if meth():
	  File "cylc-7.8.6/lib/cylc/task_pool.py", line 1061, in remove_spent_tasks
	    self.remove(itask)
	  File "cylc-7.8.6/lib/cylc/task_pool.py", line 511, in remove
	    del self.pool[itask.point][itask.identity]
	KeyError: u'glm_run_plotting.20201012T0000Z'
2020-10-13T13:48:17Z CRITICAL - Suite shutting down - u'glm_run_plotting.20201012T0000Z'
```

It looks like this was caused by the removal of a task from the graph in a restart which caused subsequent restarts to fall over during launch. Re-instating the task allowed the suite to be restarted successfully.

**Comment by hjoliver** [comment]
> It looks like this was caused by the removal of a task from the graph in a restart

Have you reproduced this @oliver-sanders ?  If I remove a task from the graph then restart a simple suite (on 7.8.x) the scheduler handles it OK:
```
2020-10-14T09:16:02+13:00 ERROR - ignoring task foo from the suite run datab
     (its task definition has probably been deleted).
     Traceback (most recent call last):
       File "/home/oliverh/cylc/cylc-flow-7.8.x/lib/cylc/task_pool.py", line 3
         self.config.get_taskdef(name),
       File "/home/oliverh/cylc/cylc-flow-7.8.x/lib/cylc/config.py", line 2189
         self.taskdefs[name] = self._get_taskdef(name)
       File "/home/oliverh/cylc/cylc-flow-7.8.x/lib/cylc/config.py", line 2203
         raise SuiteConfigError("Task not defined: %s" % name)
     SuiteConfigError: Task not defined: foo
```

**Comment by oliver-sanders** [comment]
No, I've not reproduced it yet.

**Comment by oliver-sanders** [comment]
Reported again, this time with 7.8.7

**Comment by hjoliver** [comment]
Probably won't affect Cylc 8, as "remove spent tasks" is a spawn-on-submit thing.
