### ISSUE TITLE
"FileExistsError: [Errno 17] File exists: .../source" error but workflow is installed anyway

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-flow#4406]
**Describe the bug**

While testing the UI, I always end up with a mix of good workflows, and some that I have changed so much that they don't even run anymore (I rename things in files, move folders, change the SQLite DB, whatnot :gear: :hammer: ).

I found one scenario where a traceback is raised, but Cylc proceeds to install the workflow anyway. The UI and `cylc scan` both show the workflow. You can also play the workflow with no issues :man_shrugging: 

**Release version(s) and/or repository branch(es) affected?**

`master` UIS & Flow (UI is not, but doesn't matter)

**Steps to reproduce the bug**

1. Create a workflow source (e.g. copy `~/cylc-src/five` to `~/cylc-src/deleteme`)
2. Install it a few times
  2.1. `cylc install`
  2.2. `cylc install --flow-name=deleteme/a`
3. Now start the workflows
4. Now stop the workflows (these two steps are probably not necessary, but I'm re-doing my steps after testing the UI)
5. `cylc clean deleteme/a/run1` and `cylc clean deleteme/run1`
6. Now `rm -rf ~/cylc-src/deleteme`
7. Now go back to `~/cylc-src/five` and try to install it with `cylc install --flow-name=deleteme`.
8. Voilà, now you should get the error, but the workflow is installed anyway.

**Expected behavior**

Hmmm, I think the new workflow must be installed successfully? Or maybe an error and no installation? Either of these, but not an error and install.

**Screenshots**

![image](https://user-images.githubusercontent.com/304786/133023855-057f4a4c-911c-4815-acf1-d0d126785a0b.png)

![image](https://user-images.githubusercontent.com/304786/133023903-58a86d19-a2b9-4ece-9e3d-0e2f1ef0c0fa.png)

**Additional context**

Traceback:

```bash
(venv) kinow@ranma:~/cylc-src/three$ cylc install --flow-name=deleteme
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/bin/cylc", line 33, in <module>
    sys.exit(load_entry_point('cylc-flow', 'console_scripts', 'cylc')())
  File "/home/kinow/Development/python/workspace/cylc-flow/cylc/flow/scripts/cylc.py", line 539, in main
    execute_cmd(command, *cmd_args)
  File "/home/kinow/Development/python/workspace/cylc-flow/cylc/flow/scripts/cylc.py", line 172, in execute_cmd
    COMMANDS[cmd].resolve()(*args)
  File "/home/kinow/Development/python/workspace/cylc-flow/cylc/flow/terminal.py", line 234, in wrapper
    wrapped_function(*wrapped_args, **wrapped_kwargs)
  File "/home/kinow/Development/python/workspace/cylc-flow/cylc/flow/scripts/install.py", line 142, in main
    install(parser, opts, reg)
  File "/home/kinow/Development/python/workspace/cylc-flow/cylc/flow/scripts/install.py", line 182, in install
    source_dir, rundir, _flow_name = install_workflow(
  File "/home/kinow/Development/python/workspace/cylc-flow/cylc/flow/workflow_files.py", line 1515, in install_workflow
    source_link.symlink_to(source)
  File "/home/kinow/Development/python/miniconda3/lib/python3.8/pathlib.py", line 1379, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
  File "/home/kinow/Development/python/miniconda3/lib/python3.8/pathlib.py", line 442, in symlink
    return os.symlink(a, b)
FileExistsError: [Errno 17] File exists: '/home/kinow/cylc-src/three' -> '/home/kinow/cylc-run/deleteme/_cylc-install/source'
(venv) kinow@ranma:~/cylc-src/three$ 

```

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by MetRonnie** [comment]
I think this probably related to #4322

**Comment by kinow** [comment]
You are right @MetRonnie ! Closing as duplicate, thanks!!
