### ISSUE TITLE
`cylc stop` traceback

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#4758]
- [ ] **Bug 1:** When trying to stop multiple workflows that are already stopped

    ```
    $ cylc stop foo bar
    WorkflowStopped: bar is not running
    Task exception was never retrieved
    future: <Task finished name='Task-2' coro=<run() done,
        defined at ~/github/cylc-flow/cylc/flow/scripts/stop.py:181> exception=WorkflowStopped('foo')>
    Traceback (most recent call last):
    File "~/github/cylc-flow/cylc/flow/network/__init__.py", line 78, in get_location
        contact = load_contact_file(workflow)
    File "~/github/cylc-flow/cylc/flow/workflow_files.py", line 610, in load_contact_file
        raise ServiceFileError("Couldn't load contact file")
    cylc.flow.exceptions.ServiceFileError: Couldn't load contact file

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "~/github/cylc-flow/cylc/flow/scripts/stop.py", line 214, in run
        pclient = get_client(workflow_id, timeout=options.comms_timeout)
    File "~/github/cylc-flow/cylc/flow/network/client_factory.py", line 55, in get_client
        return get_runtime_client(get_comms_method(), workflow, timeout=timeout)
    File "~/github/cylc-flow/cylc/flow/network/client_factory.py", line 49, in get_runtime_client
        return WorkflowRuntimeClient(workflow, timeout=timeout)
    File "~/github/cylc-flow/cylc/flow/network/client.py", line 131, in __init__
        host, port, _ = get_location(workflow)
    File "~/github/cylc-flow/cylc/flow/network/__init__.py", line 80, in get_location
        raise WorkflowStopped(workflow)
    cylc.flow.exceptions.WorkflowStopped: foo is not running
    ```

- [ ] **Bug 2:** When trying to stop at multiple cycles/tasks for the same workflow

    ```
    $ cylc stop datetime-cycling //2000 //2001
    Traceback (most recent call last):
    File "~/.conda/envs/cylc8/bin/cylc", line 33, in <module>
        sys.exit(load_entry_point('cylc-flow', 'console_scripts', 'cylc')())
    File "~/github/cylc-flow/cylc/flow/scripts/cylc.py", line 675, in main
        execute_cmd(command, *cmd_args)
    File "~/github/cylc-flow/cylc/flow/scripts/cylc.py", line 285, in execute_cmd
        entry_point.resolve()(*args)
    File "~/github/cylc-flow/cylc/flow/terminal.py", line 226, in wrapper
        wrapped_function(*wrapped_args, **wrapped_kwargs)
    File "~/github/cylc-flow/cylc/flow/scripts/stop.py", line 263, in main
        rets = call_multi(
    File "~/github/cylc-flow/cylc/flow/network/multi.py", line 29, in call_multi
        return asyncio.run(call_multi_async(*args, **kwargs))
    File "~/.conda/envs/cylc8/lib/python3.9/asyncio/runners.py", line 44, in run
        return loop.run_until_complete(main)
    File "~/.conda/envs/cylc8/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
        return future.result()
    File "~/github/cylc-flow/cylc/flow/network/multi.py", line 88, in call_multi_async
        async for (workflow_id, *args), result in unordered_map(
    File "~/github/cylc-flow/cylc/flow/async_util.py", line 460, in unordered_map
        yield task._args, task.result()
    File "~/github/cylc-flow/cylc/flow/scripts/stop.py", line 187, in run
        raise Exception('Multiple TODO')
    Exception: Multiple TODO
    ```

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
> Exception: Multiple TODO

MB :facepalm:
