### ISSUE TITLE
no detach: KeyboardInterrupt traceback

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#4914]
Ctrl+C'ing the scheduler in no-detach mode is not being handled as elegantly as it once was. We are now getting `concurrent.futures._base.CancelledError` traceback. 

**Pull requests welcome!**

**Comment by MetRonnie** [comment]
The `CancelledError` is raised by asyncio when it detects a `KeyboardInterrupt`. If we do not want that traceback in the scheduler log I think it's possible to detect when the `CancelledError` is due to a `KeyboardInterrupt` and avoid traceback in that circumstance, maybe just log "Keyboard interrupt". Not sure how to deal with the duplicate traceback dumped to stderr, is that done in `terminal.py`?

**Comment by oliver-sanders** [comment]
Perhaps we can intercept the `KeyboardInterrupt` at the appropriate level to make the traceback nicer.

We didn't do anything fancy to handle `KeyboardInterrupt` but it didn't use to error like this.

**Comment by MetRonnie** [comment]
In Python 3.11+ the traceback is a lot smaller 
```
2024-04-03T11:06:26+01:00 INFO - [20000101T0000Z/foo:waiting(runahead)] => waiting
^C2024-04-03T11:06:58+01:00 ERROR -
    Traceback (most recent call last):
      File "~/github/cylc-flow/cylc/flow/scheduler.py", line 651, in run_scheduler
        await self._main_loop()
      File "~/github/cylc-flow/cylc/flow/scheduler.py", line 1843, in _main_loop
        await asyncio.sleep(duration)
      File "~/.conda/envs/cylc8/lib/python3.11/asyncio/tasks.py", line 649, in sleep
        return await future
               ^^^^^^^^^^^^
    asyncio.exceptions.CancelledError
2024-04-03T11:06:58+01:00 CRITICAL - Workflow shutting down
2024-04-03T11:06:58+01:00 INFO - DONE
```
