### ISSUE TITLE
Task status not getting through to UI Server before shutdown?

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-flow#5092]
#### Describe the bug

A quick-running workflow does not update the task status in the UI at shutdown.

#### Release version(s) and/or repository branch(es) affected?

8.0.x

#### Steps to reproduce the bug

Run the simple "one" workflow from the UI
```
[scheduler]
    allow implicit tasks = True
[scheduling]
    initial cycle point = 1
    cycling mode = integer
    [[graph]]
        R1 = foo
```
It starts up, runs and shuts down without updating the task status at the end

![image](https://user-images.githubusercontent.com/61982285/185969932-9816814f-a298-4a13-bfe5-28fc11464d06.png)

#### Additional context

Scheduler log:
```
...
2022-08-22T17:10:15+01:00 INFO - [1/foo running job:01 flows:1] (received)succeeded at 2022-08-22T17:10:14+01:00
2022-08-22T17:10:15+01:00 INFO - [1/foo running job:01 flows:1] => succeeded
2022-08-22T17:10:15+01:00 INFO - Workflow shutting down - AUTOMATIC
2022-08-22T17:10:15+01:00 INFO - DONE
```
UI Server log:
```
[I 2022-08-22 17:10:08.015 CylcUIServer] $ cylc play --color=never --mode live Mist
[I 2022-08-22 17:10:09.557 CylcHubApp log:189] 200 POST /user/rdutta/cylc/graphql (rdutta@::ffff:10.217.214.23) 1551.38ms
[I 2022-08-22 17:10:09.716 CylcUIServer] [data-store] connect_workflow('~rdutta/Mist', <dict>)
[I 2022-08-22 17:10:15.731 CylcUIServer] [data-store] disconnect_workflow('~rdutta/Mist')
```

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
I think the server isn't clearing the publish queue before before sending the shutdown signal and stopping, something like this might work:

```diff
diff --git a/cylc/flow/network/server.py b/cylc/flow/network/server.py
index 6802bf0ce..94ce3dddb 100644
--- a/cylc/flow/network/server.py
+++ b/cylc/flow/network/server.py
@@ -217,6 +217,7 @@ class WorkflowRuntimeServer:
         if self.replier:
             self.replier.stop(stop_loop=False)
         if self.publisher:
+            self._publish()
             await self.publisher.publish(
                 [(b'shutdown', str(reason).encode('utf-8'))]
             )
@@ -245,13 +246,16 @@ class WorkflowRuntimeServer:
             self.replier.listener()
 
             # Publish all requested/queued.
-            while self.publish_queue.qsize():
-                articles = self.publish_queue.get()
-                self.loop.run_until_complete(self.publisher.publish(articles))
+            self._publish()
 
             # Yield control to other threads
             sleep(self.OPERATE_SLEEP_INTERVAL)
 
+    def _publish(self):
+        while self.publish_queue.qsize():
+            articles = self.publish_queue.get()
+            self.loop.run_until_complete(self.publisher.publish(articles))
+
     def receiver(self, message):
         """Process incoming messages and coordinate response.
```

**Comment by MetRonnie** [comment]
Unfortunately get an error for that
```
ERROR - Cannot run the event loop while another loop is running
    Traceback (most recent call last):
      File "~/cylc-flow/cylc/flow/scheduler.py", line 1707, in shutdown
        await self._shutdown(reason)
      File "~/cylc-flow/cylc/flow/scheduler.py", line 1767, in _shutdown
        await self.server.stop(reason)
      File "~/cylc-flow/cylc/flow/network/server.py", line 220, in stop
        self._publish()
      File "~/cylc-flow/cylc/flow/network/server.py", line 257, in _publish
        self.loop.run_until_complete(self.publisher.publish(articles))
      File "~/.conda/envs/cylc8/lib/python3.9/asyncio/base_events.py", line 623, in run_until_complete
        self._check_running()
      File "~/.conda/envs/cylc8/lib/python3.9/asyncio/base_events.py", line 585, in _check_running
        raise RuntimeError(
    RuntimeError: Cannot run the event loop while another loop is running
~/cylc-flow/cylc/flow/scheduler_cli.py:421: RuntimeWarning: coroutine 'WorkflowPublisher.publish' was never awaited
  ret = 3
```

**Comment by oliver-sanders** [comment]
(would need to make `def _publish(self)` `async` and sort out the event loop stuff)
