### ISSUE TITLE
Raise Error when playing a running Cylc 7 workflow

### ISSUE THREAD

**Issue by datamel** [cylc/cylc-flow#5317]
Niche bug but one that may crop up with users.

**Release version(s) and/or repository branch(es) affected?**

Current `Master` branch

**Steps to reproduce the bug**

Run a suite/workflow at Cylc 7.

Play this running workflow at Cylc 8
Traceback occurs: 

```
Traceback (most recent call last):
  File "…/cylc/flow/workflow_files.py", line 507, in detect_old_contact_file
    old_pid: str = contact_data[ContactFileFields.PID]
KeyError: 'CYLC_WORKFLOW_PID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "…/cylc", line 33, in <module>
    sys.exit(load_entry_point('cylc-flow', 'console_scripts', 'cylc')())
  File "…/cylc/flow/scripts/cylc.py", line 653, in main
    execute_cmd(command, *cmd_args)
  File "…/cylc/flow/scripts/cylc.py", line 286, in execute_cmd
    entry_point.resolve()(*args)
  File "…/cylc/flow/terminal.py", line 232, in wrapper
    wrapped_function(*wrapped_args, **wrapped_kwargs)
  File "…/cylc/flow/scheduler_cli.py", line 624, in play
    return _play(parser, options, id_)
  File "…/cylc/flow/scheduler_cli.py", line 634, in _play
    return scheduler_cli(options, id_)
  File "…/cylc/flow/scheduler_cli.py", line 374, in scheduler_cli
    _resume(workflow_id, options)
  File "…/cylc/flow/scheduler_cli.py", line 433, in _resume
    detect_old_contact_file(workflow_id)
  File "…/cylc/flow/workflow_files.py", line 512, in detect_old_contact_file
    raise Exception(f'Found contact file with incomplete data:\n{exc}.')
Exception: Found contact file with incomplete data:
'CYLC_WORKFLOW_PID'.
```

**Expected behavior**

Expect clean error raised

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment]
Closed by #5313
