### ISSUE TITLE
data_store_mgr: traceback

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#5388]
Reported traceback, requires investigation:

```
2023-03-01T16:47:40Z ERROR - None has type NoneType, but expected one of: bytes, unicode                                           
    Traceback (most recent call last):    
      File "/cylc/flow/scheduler.py", line 634, in run_scheduler    
        await self.main_loop()    
      File "/cylc/flow/scheduler.py", line 1562, in main_loop    
        self.proc_pool.process()    
      File "/cylc/flow/subprocpool.py", line 224, in process    
        self._proc_exit(    
      File "/cylc/flow/subprocpool.py", line 206, in _proc_exit    
        self._run_command_exit(    
      File "/cylc/flow/subprocpool.py", line 534, in _run_command_exit    
        _run_callback(callback, callback_args)    
      File "/cylc/flow/subprocpool.py", line 481, in _run_callback    
        callback(ctx, *args_)    
      File "/cylc/flow/task_job_mgr.py", line 781, in _poll_task_jobs_callback    
        self._manip_task_jobs_callback(    
      File "/cylc/flow/task_job_mgr.py", line 766, in _manip_task_jobs_callback    
        callback(workflow, itask, ctx, line)    
      File "/cylc/flow/task_job_mgr.py", line 874, in _poll_task_job_callback    
        self.task_events_mgr.process_message(    
      File "/cylc/flow/task_events_mgr.py", line 681, in process_message    
        self.data_store_mgr.delta_job_attr(    
      File "/cylc/flow/data_store_mgr.py", line 2160, in delta_job_attr    
        setattr(j_delta, attr_key, attr_val)    
    TypeError: None has type NoneType, but expected one of: bytes, unicode    
2023-03-01T16:47:40Z CRITICAL - Workflow shutting down - None has type NoneType, but expected one of: bytes, unicode    
2023-03-01T16:47:40Z INFO - [20230228T1800Z/epoch_archiving submitted job:01 flows:1] (polled)submitted at 2023-03-01T04:23:08Z
2023-03-01T16:47:40Z ERROR - None has type NoneType, but expected one of: bytes, unicode    
    Traceback (most recent call last):    
      File "/cylc/flow/scheduler.py", line 634, in run_scheduler    
        await self.main_loop()    
      File "/cylc/flow/scheduler.py", line 1562, in main_loop    
        self.proc_pool.process()    
      File "/cylc/flow/subprocpool.py", line 224, in process    
        self._proc_exit(    
      File "/cylc/flow/subprocpool.py", line 206, in _proc_exit    
        self._run_command_exit(    
      File "/cylc/flow/subprocpool.py", line 534, in _run_command_exit    
        _run_callback(callback, callback_args)    
      File "/cylc/flow/subprocpool.py", line 481, in _run_callback    
        callback(ctx, *args_)    
      File "/cylc/flow/task_job_mgr.py", line 781, in _poll_task_jobs_callback    
        self._manip_task_jobs_callback(    
      File "/cylc/flow/task_job_mgr.py", line 766, in _manip_task_jobs_callback    
        callback(workflow, itask, ctx, line)    
      File "/cylc/flow/task_job_mgr.py", line 874, in _poll_task_job_callback    
        self.task_events_mgr.process_message(    
      File "/cylc/flow/task_events_mgr.py", line 681, in process_message    
        self.data_store_mgr.delta_job_attr(    
      File "/cylc/flow/data_store_mgr.py", line 2160, in delta_job_attr    
        setattr(j_delta, attr_key, attr_val)    
    TypeError: None has type NoneType, but expected one of: bytes, unicode    
    During handling of the above exception, another exception occurred:    
    Traceback (most recent call last):    
      File "/cylc/flow/scheduler.py", line 1775, in _shutdown    
        self.proc_pool.terminate()    
      File "/cylc/flow/subprocpool.py", line 345, in terminate    
        self.process()    
      File "/cylc/flow/subprocpool.py", line 224, in process    
        self._proc_exit(    
      File "/cylc/flow/subprocpool.py", line 206, in _proc_exit    
        self._run_command_exit(    
      File "/cylc/flow/subprocpool.py", line 534, in _run_command_exit    
        _run_callback(callback, callback_args)    
      File "/cylc/flow/subprocpool.py", line 481, in _run_callback    
        callback(ctx, *args_)    
      File "/cylc/flow/task_job_mgr.py", line 781, in _poll_task_jobs_callback    
        self._manip_task_jobs_callback(    
      File "/cylc/flow/task_job_mgr.py", line 766, in _manip_task_jobs_callback    
        callback(workflow, itask, ctx, line)    
      File "/cylc/flow/task_job_mgr.py", line 874, in _poll_task_job_callback    
        self.task_events_mgr.process_message(    
      File "/cylc/flow/task_events_mgr.py", line 681, in process_message    
        self.data_store_mgr.delta_job_attr(    
      File "/cylc/flow/data_store_mgr.py", line 2160, in delta_job_attr    
        setattr(j_delta, attr_key, attr_val)    
    TypeError: None has type NoneType, but expected one of: bytes, unicode    
2023-03-01T16:47:40Z WARNING - Orphaned tasks:    
    * 20230228T1800Z/epoch_archiving (submitted)    
    * 20230301T0000Z/epoch_prepare_mogreps (submitted)    
```

**Comment by oliver-sanders** [comment]
The remote job.err file for `20230228T1800Z/epoch_archiving` (this poll was the last message in the log before the crash):

```
2023-03-01T17:04:31Z INFO - Removed contact file for <workflow-id> (workflow no longer running).
WorkflowStopped: mi-aw840/run1 is not running
```

Note the job succeeded.

**Comment by oliver-sanders** [comment]
I can't see how a `setattr` statement could raise that error so I'm guessing the error reporting isn't accurate?

**Comment by hjoliver** [comment]
> I'm guessing the error reporting isn't accurate?

Do you mean by the affected user, or by our code?

**Comment by oliver-sanders** [comment]
>> I'm guessing the error reporting isn't accurate?
>
> Do you mean by the affected user, or by our code?

I mean the line in the code which the Python traceback is pointing at. I can't see how that error could originate there.

**Comment by wxtim** [comment]
I'll see if I can reproduce this.

**Comment by MetRonnie** [comment]
On Python 3.10.6 I can't reproduce the exact error while debugging when setting the value of any of `j_delta, attr_key, attr_val` with `None`. Closest I can come is
```
File "~/cylc-flow-8.1/cylc/flow/data_store_mgr.py", line 2160, in delta_job_attr
        setattr(j_delta, attr_key, attr_val)   <------------------------------------ attr_val = None
    TypeError: bad argument type for built-in operation
```

**Comment by wxtim** [comment]
Do we have more context?

**Comment by oliver-sanders** [comment]
My conclusion too.

**Comment by oliver-sanders** [comment]
A search of the error message yielded a few results but with no consistent origin.

**Comment by oliver-sanders** [comment]
```
$ grep -r 'but expected one of' .
./lib/python3.7/site-packages/google/protobuf/internal/type_checkers.py:      message = ('%.1024r has type %s, but expected one of: %s' %
```

**Comment by wxtim** [comment]
I cannot for the life of me get that error to show up.

**Comment by MetRonnie** [comment]
I stuck a breakpoint in
```
# google/protobuf/internal/type_checkers.py
class UnicodeValueChecker(object):

  """Checker used for string fields.

  Always returns a unicode value, even if the input is of type str.
  """

  def CheckValue(self, proposed_value):
    if not isinstance(proposed_value, (bytes, str)):
      message = ('%.1024r has type %s, but expected one of: %s' %
                 (proposed_value, type(proposed_value), (bytes, str)))
      raise TypeError(message)
```
but it didn't get hit during a normal workflow run

**Comment by oliver-sanders** [comment]
Under normal circumstances we wouldn't expect this error to be raised (if it were it would crash the workflow as in this case). It was something about the state of the data store or the information which was being added to the data store caused this to be raised.

**Comment by wxtim** [comment]
> I stuck a breakpoint in

I tried this too.

**Comment by MetRonnie** [comment]
> Under normal circumstances we wouldn't expect this error to be raised...

I mean I stuck a breakpoint in the top of the function

**Comment by oliver-sanders** [comment]
I can see how `attr_value` could be `None` but I can't see how that would cause the reported traceback at present.

**Comment by oliver-sanders** [comment]
Chain of events:

* A task was submitted to a remote platform, the job_id was returned and logged correctly.
* The submission was polled.
* The platform went down.
* The workflow crashed.
* The workflow was restarted.
* The submission was polled.
* The poll triggered the data store to create a delta for the job_id (despite the job_id not having changed?)
* The workflow crashed when it attempted to set the job ID on the (blank) delta.
* In the shutdown logic the workflow retried to apply this delta and failed in the same way again.

**Comment by oliver-sanders** [comment]
I've tried just about every illogical value with the `setattr` statement and cannot reproduce the original errorr:

<details>
<summary>code</summary>

<pre>
from itertools import combinations_with_replacement

from cylc.flow.data_messages_pb2 import PbJob


items = [
    None,
    b'123',
    b'',
    '123',
    '',
    [],
    [None],
    set(),
    {None},
    (),
    (None,),
    {},
    {None: None},
    {'a': None},
    True,
    False,
    0,
    123,
    -42,
    lambda x: None,
    'None',
    '[None]',
    '{"A": None}',
    'null',
    '[null]',
    '{"a": null}',
    b'None',
    b'[None]',
    b'{"A": None}',
    b'null',
    b'[null]',
    b'{"a": null}',
    '\u0e55\u0e57',
    b'\u0e55\u0e57',
]


combs = list(combinations_with_replacement(items, 2))

for b, a in combs:
    if (a, b) not in combs:
        combs.append((a, b))


for before, after in sorted(combs, key=lambda x: str(x)):
    print('#', before, after)
    try:
        j = PbJob(job_id=before)
        setattr(j, 'job_id', after)
    except Exception as exc:
        if 'but expected' in str(exc):
            raise
        print(exc)

    try:
        j = PbJob()
        setattr(j, 'job_id', after)
    except Exception as exc:
        if 'but expected' in str(exc):
            raise
        print(exc)
</pre>
</details>

Especially frustrating as the error occurred twice in a row, once when the message came in, and once on shutdown when the workflow attempted to clear out the message queue.

**Comment by oliver-sanders** [comment]
REPRODUCED!

```
from cylc.flow.data_messages_pb2 import PbJob
 
j = PbJob() : Unknown                                    
setattr(j, 'job_id', None)    
```

But with Python 3.9:

```
Traceback (most recent call last):
  File "mess.py", line 4, in <module>
    setattr(j, 'job_id', None)
TypeError: None has type NoneType, but expected one of: bytes, unicode
```

3.7 gives:

```
TypeError: bad argument type for built-in operation
```

For the same protobuf version?! Whatever.

**Comment by wxtim** [comment]
> REPRODUCED!

So close... I did this with 3.7
