### ISSUE TITLE
Cylc Validate failed to catch bad offset

### ISSUE THREAD

**Issue by ukmo-ccbunney** [cylc/cylc-flow#5448]
### Description
An invalid isodatetime in the [[xtriggers]] section can get past cylc validate and cause a suite to fail.
I'm not sure if `cylc validate` should be expected to catch this typo, but I will raise it just in case:
```
    [[xtriggers]]
        L1_trigger = wall_clock(offset=PT755MH):PT30S  # <-- bad offset
```
I meant to type `PT7H55M`, but instead made a typo and wrote an offset of `755MH`

My suite kept failing to start (it just launched immediately into a "stopped" state) and I couldn't figure out why.
I only realised my error when I checked the "Workflow log file"

```
2023-04-03T13:37:42Z ERROR - could not convert string to float: '755M'
    Traceback (most recent call last):
      File "/home/h03/fcm/cylc-8.1.2-2/lib/python3.9/site-packages/cylc/flow/cycling/iso8601.py", line 881, in interval_parse
        return _interval_parse(interval_string)
      File "/home/h03/fcm/cylc-8.1.2-2/lib/python3.9/site-packages/cylc/flow/cycling/iso8601.py", line 902, in _interval_parse
        return WorkflowSpecifics.interval_parser.parse(interval_string)
      File "/home/h03/fcm/cylc-8.1.2-2/lib/python3.9/site-packages/metomi/isodatetime/parsers.py", line 575, in parse
        value = float(value)
    ValueError: could not convert string to float: '755M'
```

Cylc validate usually shouts about these kind of isodatetime errors, but not in this case.

### Reproducible Example

Add the above section into a flow.cylc and run as usual (I use `cylc vip`)
### Expected Behaviour

Suite will validate and install ok, but will immediately show in UI as "stopped".
Check workflow log, you should see the error above.

**Comment by hjoliver** [comment]
Confirmed. Thanks for the bug report!

**Comment by hjoliver** [comment]
(Fix done, just testing it ...)
