### ISSUE TITLE
xtriggers and values with a comma breaks Cylc

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-flow#5575]
### Description

I've tested this in both Cylc7 and Cylc8 and it exists for both.
If you have a value which contains a `,`, 

### Reproducible Example

See the below snippet. First, I show validate works without a `,` in the message.
Next I put a comma in, and show it fails to validate.

NOTE: I modified the `validate.py` file to print out the values before it tries to `_coerce_type` them for reference.
You can see that the message was split on a comma.

```bash

$ cat flow.cylc
#!jinja2
{%  set A = 'Hello world' %}
[scheduler]
   allow implicit tasks=True
[scheduling]
    initial cycle point = 20200101
    [[xtriggers]]
        B = workflow_state("basic", task="b", point="%(point)s", message="{{A}}")
    [[ graph]]
        P1D = """
            @B => b
        """
$ cylc validate $PWD
"basic"
"b"
"%(point)s"
"Hello world"
Valid for cylc-8.1.3
$ vi flow.cylc
$ cylc validate $PWD
"basic"
"b"
"%(point)s"
"Hello
Traceback (most recent call last):
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/parsec/validate.py", line 1052, in _coerce_type
    val = int(value)
ValueError: invalid literal for int() with base 10: '"Hello'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/parsec/validate.py", line 1055, in _coerce_type
    val = float(value)
ValueError: could not convert string to float: '"Hello'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/terminal.py", line 232, in wrapper
    wrapped_function(*wrapped_args, **wrapped_kwargs)
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/scripts/validate.py", line 132, in main
    _main(parser, options, workflow_id)
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/scripts/validate.py", line 136, in _main
    asyncio.run(wrapped_main(parser, options, workflow_id))
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/scripts/validate.py", line 154, in wrapped_main
    cfg = WorkflowConfig(
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/config.py", line 308, in __init__
    self.pcfg = RawWorkflowConfig(
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/cfgspec/workflow.py", line 2042, in __init__
    self.loadcfg(fpath, "workflow definition")
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/parsec/config.py", line 86, in loadcfg
    self.validate(sparse)
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/parsec/config.py", line 96, in validate
    return self.validator(sparse, self.spec)
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/parsec/validate.py", line 1139, in cylc_config_validate
    return CylcConfigValidator().validate(cfg_root, spec_root)
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/parsec/validate.py", line 230, in validate
    cfg[key] = self.coercers[specval.vdr](value, keys + [key])
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/parsec/validate.py", line 1031, in coerce_xtrigger
    kwargs[key.strip()] = cls._coerce_type(val.strip())
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/parsec/validate.py", line 1063, in _coerce_type
    val = cls.strip_and_unquote([], value)
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/parsec/validate.py", line 539, in strip_and_unquote
    raise IllegalValueError("string", keys, value)
cylc.flow.parsec.exceptions.IllegalValueError: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "${CONDA_PREFIX}/cylc-8.1.4/bin/cylc", line 10, in <module>
    sys.exit(main())
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/scripts/cylc.py", line 656, in main
    execute_cmd(command, *cmd_args)
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/scripts/cylc.py", line 286, in execute_cmd
    entry_point.resolve()(*args)
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/terminal.py", line 241, in wrapper
    EXC_EXIT.format(
  File "${CONDA_PREFIX}/cylc-8.1.4/lib/python3.10/site-packages/cylc/flow/parsec/exceptions.py", line 240, in __str__
    msg += itemstr(self.keys[:-1], self.keys[-1], value=self.value)
IndexError: list index out of range

```

### Expected Behaviour

A comma in a value should not break xtriggers.
At minimum, a way to escape a comma here, but not have the escape character passed into the xtrigger itself.

**Comment by oliver-sanders** [comment]
https://github.com/cylc/cylc-flow/issues/5588
