### ISSUE TITLE
Cylc dependency on rsync isn't documented

### ISSUE THREAD

**Issue by elliotfontaine** [cylc/cylc-flow#6116]
### Description

I've recently installed Cylc on a Debian VM and came across this error when installing a workflow:
```python
Traceback (most recent call last):
  File "/home/fontain/miniforge3/envs/cylc/bin/cylc", line 10, in <module>
    sys.exit(main())
  File "/home/fontain/miniforge3/envs/cylc/lib/python3.9/site-packages/cylc/flow/scripts/cylc.py", line 660, in main
    execute_cmd(command, *cmd_args)
  File "/home/fontain/miniforge3/envs/cylc/lib/python3.9/site-packages/cylc/flow/scripts/cylc.py", line 286, in execute_cmd
    entry_point.resolve()(*args)
  File "/home/fontain/miniforge3/envs/cylc/lib/python3.9/site-packages/cylc/flow/terminal.py", line 232, in wrapper
    wrapped_function(*wrapped_args, **wrapped_kwargs)
  File "/home/fontain/miniforge3/envs/cylc/lib/python3.9/site-packages/cylc/flow/scripts/install.py", line 271, in main
    install_cli(opts, id_)
  File "/home/fontain/miniforge3/envs/cylc/lib/python3.9/site-packages/cylc/flow/scripts/install.py", line 279, in install_cli
    wf_name, wf_id = install(opts, id_)
  File "/home/fontain/miniforge3/envs/cylc/lib/python3.9/site-packages/cylc/flow/scripts/install.py", line 320, in install
    source_dir, rundir, workflow_name, workflow_id = install_workflow(
  File "/home/fontain/miniforge3/envs/cylc/lib/python3.9/site-packages/cylc/flow/install.py", line 335, in install_workflow
    proc = Popen(rsync_cmd, stdout=PIPE, stderr=PIPE, text=True)  # nosec
  File "/home/fontain/miniforge3/envs/cylc/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/fontain/miniforge3/envs/cylc/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'rsync'
```

Indeed, `rsync` isn't installed on the system. But it isn't listed as a dependency in [Cylc documentation](https://cylc.github.io/cylc-doc/stable/html/installation.html#non-python-requirements).

### Reproducible Example

cylc conda environment
```yml
name: cylc
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pytest=8.0
  - cylc-flow=8.2
  - cylc-uiserver
  - metomi-rose=2.2
  - cylc-rose=1.3
```

flow.cylc
```ini
[scheduler]
    allow implicit tasks = True
[scheduling]
    cycling mode = integer
    initial cycle point = 1
    [[graph]]
        P1 = """
            a & c => b => d & f
            f[-P1] => c  # (1)
        """
        P2 = """
            d => e
            d[-P1] => a  # (2)
        """
        2/P2 = """
            e[-P1] => a  # (3)
        """
```

Command to replicate the error:
`cylc install cycling-tutorial`

### Expected Behaviour

Have the `rsync` dependency be documented alongside the `bash` and `GNU coreutils` ones.

**Comment by oliver-sanders** [comment]
These dependencies have been recently added to the installation section, the docs will be updated when Cylc 8.3.0 is released (very soon):

https://github.com/cylc/cylc-doc/commit/bc964b2ad4efdfed90878ce8d530ac2d40adbce7
