### ISSUE TITLE
sys.exit traceback running 8.3+ on MacOS

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-flow#6291]
Traceback appears in terminal on start-up in detaching mode, since 8.3.0 (8.2.7 was fine)
The workflow still runs, but a similar traceback appears in the scheduler log on shutdown

```
$ cylc play bug/run20

 ▪ ■  Cylc Workflow Engine 8.3.0.dev
 ██   Copyright (C) 2008-2023 NIWA
▝▘    & British Crown (Met Office) & Contributors

2024-08-08T11:48:35+12:00 INFO - Extracting job.sh to /Users/oliver/cylc-
    run/bug/run20/.service/etc/job.sh
Traceback (most recent call last):
  File "/Users/oliver/miniforge3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/oliver/miniforge3/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/oliver/miniforge3/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/oliver/miniforge3/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/oliver/miniforge3/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/oliver/cylc/cylc-flow/cylc/flow/scheduler_cli.py", line 417, in scheduler_cli
    daemonize(scheduler)
  File "/Users/oliver/cylc/cylc-flow/cylc/flow/daemonize.py", line 121, in daemonize
    sys.exit(0)
SystemExit: 0
```

**Comment by hjoliver** [comment]
The offending commit is apparently this one:

```console
$ git bisect bad
8140c6f6a2fa4c7ac44ded0f60bdcdf3bd145bb2 is the first bad commit
commit 8140c6f6a2fa4c7ac44ded0f60bdcdf3bd145bb2 (HEAD)
Author: Mark Dawson <mark.dawson@metoffice.gov.ukpython>
Date:   Wed Nov 1 17:00:39 2023 +0000

    made reinstall work on multiple workflows

    flake8 clean up

    fixed unit tests

    fixed cylc-combination/01-vr-reload functional test

    fixed cylc-reinstall/00-simple.t functional test

    updated change log

    review amends

 changes.d/5803.feat.md                      |  1 +
 cylc/flow/scheduler_cli.py                  | 46 ++++++++++++++++++++++++++++------------------
 cylc/flow/scripts/reinstall.py              | 35 +++++++++++++++++++++--------------
 cylc/flow/scripts/validate_reinstall.py     | 25 +++++++++++++++----------
 tests/functional/cylc-reinstall/00-simple.t |  1 +
 tests/integration/test_reinstall.py         | 49 +++++++++++++++++++++++++------------------------
 6 files changed, 91 insertions(+), 66 deletions(-)
 create mode 100644 changes.d/5803.feat.md
```

**Comment by hjoliver** [comment]
Probable cause: https://github.com/cylc/cylc-flow/pull/5803/files#r1708191219

**Comment by hjoliver** [comment]
It's something to do with the asyncio changes in `scheduler_cli` but I haven't got my head around it yet.

**Comment by oliver-sanders** [comment]
Aah.

The asyncio stuff in `scheduler_cli` is highly abnormal due to the daemonization step.

If the process is being daemonized, then control is passed over to the new fork. However, asyncio is not yet initalised in that fork so we have to open a new loop.

This has resulted in the highly illogical situation where `asyncio.run` is called from within an `async` function when detaching (to start the new loop):

https://github.com/cylc/cylc-flow/blob/b46f35ae034a3c167ea2f585ffe4f9c4a9144a2a/cylc/flow/scheduler_cli.py#L425-L433

Calling `asyncio.run` from within an `async` function should not work (the loop is already running and asyncio does not tolerate nesting), however, it works because by this point in the code we are actually running in a new fork.

**Comment by hjoliver** [comment]
> Traceback aside, is this symptomless?
>
> If so, is this just Python reporting the sys.exit call?

Yes I think that's right.
